//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUTHUE
    {
        public string MAPHIEU { get; set; }
        public string MAPHONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public string LOAITHUE { get; set; }
        public string GHICHU { get; set; }
    
        public virtual PHIEUTHUE PHIEUTHUE { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
