//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public string MAPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYHOADON { get; set; }
        public Nullable<decimal> KHUYENMAI { get; set; }
        public Nullable<decimal> SOTIENPHAITRA { get; set; }
        public string TINHTRANG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual PHIEUTHUE PHIEUTHUE { get; set; }
    }
}
